api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-community/rust"
  id = "paketo-community/rust"
  name = "Rust Build Pack"
  version = "0.0.9"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/rust-dist"
    version = "0.0.9"

  [[order.group]]
    id = "paketo-community/cargo-install"
    version = "0.0.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.0.0"
