api = "0.2"

[buildpack]
  homepage = "https://github.com/dmikusa/rust-cnb"
  id = "com.mikusa.rust"
  name = "Rust Build Pack"
  version = "0.0.9"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "com.mikusa.rust-dist"
    uri = "docker://dmikusa/rust-dist:v0.0.7"

  [[metadata.dependencies]]
    id = "com.mikusa.rust-cargo"
    url = "docker://dmikusa/rust-cargo:v0.0.3"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/procfile"
    url = "docker://gcr.io/paketo-buildpacks/procfile:3.0.0"

[[order]]

  [[order.group]]
    id = "com.mikusa.rust-dist"
    version = "0.0.7"

  [[order.group]]
    id = "com.mikusa.rust-cargo"
    version = "0.0.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.0.0"
