api = "0.2"

[buildpack]
  id = "paketo-community/rust"
  name = "Rust Build Pack"
  version = "0.0.9"
  homepage = "https://github.com/paketo-community/rust"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketocommunity/rust-dist"
    uri = "docker://paketocommunity/rust-dist:v0.0.7"

  [[metadata.dependencies]]
    id = "paketocommunity/cargo-install"
    url = "docker://paketocommunity/rust-cargo:v0.0.3"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/procfile"
    url = "docker://gcr.io/paketo-buildpacks/procfile:4.0.0"

[[order]]

  [[order.group]]
    id = "paketocommunity/rust-dist"
    version="0.0.7"

  [[order.group]]
    id = "paketocommunity/cargo-install"
    version="0.0.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version="4.0.0"
    optional = true
